
services:

  redis:
    image: redis:6-alpine
    container_name: hng_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - internal
      
  # ── Frontend ───────────────────────────────────────────────────────────
  frontend:
    build: ./frontend
    container_name: hng_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - internal

  # ── API ───────────────────────────────────────────────────────────────
  api:
    build: ./api
    container_name: hng_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - worker
    networks:
      - internal

  # ── Worker ───────────────────────────────────────────────────────────
  worker:
    build: ./worker
    container_name: hng_worker
    restart: unless-stopped
    networks:
      - internal

networks:
  internal: